---
- name: Grab k3 token from control
  hosts: control
  become: yes
  gather_facts: no

  tasks:
    - name: Read K3s token
      ansible.builtin.slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: k3s_token

    - name: Print agent join token
      ansible.builtin.debug:
        msg: "{{ k3s_token.content | b64decode | trim }}"


- name 